"""add_tickerflow_tables

Revision ID: e4e38ec36752
Revises: 005
Create Date: 2026-07-29 16:43:05.684203
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e4e38ec36752'
down_revision: Union[str, None] = '005'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collection_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('requested_sources', sa.JSON(), nullable=False),
    sa.Column('completed_sources', sa.JSON(), nullable=False),
    sa.Column('request_count', sa.Integer(), nullable=False),
    sa.Column('error_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collection_runs_symbol'), 'collection_runs', ['symbol'], unique=False)
    op.create_table('price_bars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'trade_date', name='uq_price_bar')
    )
    op.create_index(op.f('ix_price_bars_symbol'), 'price_bars', ['symbol'], unique=False)
    op.create_index(op.f('ix_price_bars_trade_date'), 'price_bars', ['trade_date'], unique=False)
    op.create_table('quota_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('period', sa.String(length=7), nullable=False),
    sa.Column('used_requests', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'period', name='uq_quota_period')
    )
    op.create_table('source_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('collection_run_id', sa.Integer(), nullable=True),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('company_name', sa.String(length=256), nullable=True),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('found', sa.Boolean(), nullable=False),
    sa.Column('buzz_score', sa.Float(), nullable=True),
    sa.Column('mentions', sa.Integer(), nullable=True),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('bullish_pct', sa.Float(), nullable=True),
    sa.Column('bearish_pct', sa.Float(), nullable=True),
    sa.Column('trend', sa.String(length=32), nullable=True),
    sa.Column('unique_posts', sa.Integer(), nullable=True),
    sa.Column('coverage_count', sa.Integer(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('raw_payload', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_snapshots_collection_run_id'), 'source_snapshots', ['collection_run_id'], unique=False)
    op.create_index(op.f('ix_source_snapshots_fetched_at'), 'source_snapshots', ['fetched_at'], unique=False)
    op.create_index(op.f('ix_source_snapshots_source'), 'source_snapshots', ['source'], unique=False)
    op.create_index(op.f('ix_source_snapshots_symbol'), 'source_snapshots', ['symbol'], unique=False)
    op.create_table('ticker_daily_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('metric_date', sa.Date(), nullable=False),
    sa.Column('mentions', sa.Integer(), nullable=True),
    sa.Column('buzz_score', sa.Float(), nullable=True),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('bullish_pct', sa.Float(), nullable=True),
    sa.Column('bearish_pct', sa.Float(), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'source', 'metric_date', name='uq_daily_metric')
    )
    op.create_index(op.f('ix_ticker_daily_metrics_metric_date'), 'ticker_daily_metrics', ['metric_date'], unique=False)
    op.create_index(op.f('ix_ticker_daily_metrics_source'), 'ticker_daily_metrics', ['source'], unique=False)
    op.create_index(op.f('ix_ticker_daily_metrics_symbol'), 'ticker_daily_metrics', ['symbol'], unique=False)
    op.alter_column('channels', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('channels', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('channels_youtube_channel_id_key'), 'channels', type_='unique')
    op.drop_index(op.f('ix_channels_youtube_channel_id'), table_name='channels')
    op.create_index(op.f('ix_channels_youtube_channel_id'), 'channels', ['youtube_channel_id'], unique=True)
    op.alter_column('predictions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_predictions_text_search'), table_name='predictions', postgresql_using='gin')
    op.alter_column('speaker_ticker_aggregation', 'total_mentions',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('speaker_ticker_aggregation', 'explicit_mentions',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('speaker_ticker_aggregation', 'implicit_mentions',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('speaker_ticker_aggregation', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_speaker_ticker_agg_channel_id'), table_name='speaker_ticker_aggregation')
    op.drop_index(op.f('ix_speaker_ticker_agg_ticker'), table_name='speaker_ticker_aggregation')
    op.create_index(op.f('ix_speaker_ticker_aggregation_channel_id'), 'speaker_ticker_aggregation', ['channel_id'], unique=False)
    op.create_index(op.f('ix_speaker_ticker_aggregation_ticker'), 'speaker_ticker_aggregation', ['ticker'], unique=False)
    op.alter_column('theme_hierarchy', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('theme_ticker_mappings', 'source',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'curated'::character varying"))
    op.drop_index(op.f('ix_transcript_segments_embedding_cosine'), table_name='transcript_segments', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.drop_index(op.f('ix_transcript_segments_text_search'), table_name='transcript_segments', postgresql_using='gin')
    op.alter_column('videos', 'transcript_status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('videos', 'processed',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('videos', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('videos_youtube_video_id_key'), 'videos', type_='unique')
    op.drop_index(op.f('ix_videos_youtube_video_id'), table_name='videos')
    op.create_index(op.f('ix_videos_youtube_video_id'), 'videos', ['youtube_video_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_videos_youtube_video_id'), table_name='videos')
    op.create_index(op.f('ix_videos_youtube_video_id'), 'videos', ['youtube_video_id'], unique=False)
    op.create_unique_constraint(op.f('videos_youtube_video_id_key'), 'videos', ['youtube_video_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('videos', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('videos', 'processed',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('videos', 'transcript_status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
    op.create_index(op.f('ix_transcript_segments_text_search'), 'transcript_segments', [sa.literal_column("to_tsvector('english'::regconfig, text)")], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_transcript_segments_embedding_cosine'), 'transcript_segments', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.alter_column('theme_ticker_mappings', 'source',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'curated'::character varying"))
    op.alter_column('theme_hierarchy', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_speaker_ticker_aggregation_ticker'), table_name='speaker_ticker_aggregation')
    op.drop_index(op.f('ix_speaker_ticker_aggregation_channel_id'), table_name='speaker_ticker_aggregation')
    op.create_index(op.f('ix_speaker_ticker_agg_ticker'), 'speaker_ticker_aggregation', ['ticker'], unique=False)
    op.create_index(op.f('ix_speaker_ticker_agg_channel_id'), 'speaker_ticker_aggregation', ['channel_id'], unique=False)
    op.alter_column('speaker_ticker_aggregation', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('speaker_ticker_aggregation', 'implicit_mentions',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('speaker_ticker_aggregation', 'explicit_mentions',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('speaker_ticker_aggregation', 'total_mentions',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.create_index(op.f('ix_predictions_text_search'), 'predictions', [sa.literal_column("to_tsvector('english'::regconfig, prediction_text)")], unique=False, postgresql_using='gin')
    op.alter_column('predictions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_channels_youtube_channel_id'), table_name='channels')
    op.create_index(op.f('ix_channels_youtube_channel_id'), 'channels', ['youtube_channel_id'], unique=False)
    op.create_unique_constraint(op.f('channels_youtube_channel_id_key'), 'channels', ['youtube_channel_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('channels', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('channels', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_ticker_daily_metrics_symbol'), table_name='ticker_daily_metrics')
    op.drop_index(op.f('ix_ticker_daily_metrics_source'), table_name='ticker_daily_metrics')
    op.drop_index(op.f('ix_ticker_daily_metrics_metric_date'), table_name='ticker_daily_metrics')
    op.drop_table('ticker_daily_metrics')
    op.drop_index(op.f('ix_source_snapshots_symbol'), table_name='source_snapshots')
    op.drop_index(op.f('ix_source_snapshots_source'), table_name='source_snapshots')
    op.drop_index(op.f('ix_source_snapshots_fetched_at'), table_name='source_snapshots')
    op.drop_index(op.f('ix_source_snapshots_collection_run_id'), table_name='source_snapshots')
    op.drop_table('source_snapshots')
    op.drop_table('quota_usage')
    op.drop_index(op.f('ix_price_bars_trade_date'), table_name='price_bars')
    op.drop_index(op.f('ix_price_bars_symbol'), table_name='price_bars')
    op.drop_table('price_bars')
    op.drop_index(op.f('ix_collection_runs_symbol'), table_name='collection_runs')
    op.drop_table('collection_runs')
    # ### end Alembic commands ###
